// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJFSxJkOM2ejZ8OLw96CBmV0TGKQu0pmw',
    appId: '1:452109269173:web:17a14203ebe8c7fb5ca6fc',
    messagingSenderId: '452109269173',
    projectId: 'blood-donation-hci',
    authDomain: 'blood-donation-hci.firebaseapp.com',
    storageBucket: 'blood-donation-hci.firebasestorage.app',
    measurementId: 'G-W4236BV0N7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGfLi7G01KqZrxIvLGxtHD6BZsBlO82XE',
    appId: '1:452109269173:android:e8084ca74d5bd55f5ca6fc',
    messagingSenderId: '452109269173',
    projectId: 'blood-donation-hci',
    storageBucket: 'blood-donation-hci.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcS6SD8ykeINpt13m4li0aMqAfARUjoI0',
    appId: '1:452109269173:ios:fb5fcc1c903bda415ca6fc',
    messagingSenderId: '452109269173',
    projectId: 'blood-donation-hci',
    storageBucket: 'blood-donation-hci.firebasestorage.app',
    iosBundleId: 'com.example.hci',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcS6SD8ykeINpt13m4li0aMqAfARUjoI0',
    appId: '1:452109269173:ios:fb5fcc1c903bda415ca6fc',
    messagingSenderId: '452109269173',
    projectId: 'blood-donation-hci',
    storageBucket: 'blood-donation-hci.firebasestorage.app',
    iosBundleId: 'com.example.hci',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJFSxJkOM2ejZ8OLw96CBmV0TGKQu0pmw',
    appId: '1:452109269173:web:27f3e290eab64bbe5ca6fc',
    messagingSenderId: '452109269173',
    projectId: 'blood-donation-hci',
    authDomain: 'blood-donation-hci.firebaseapp.com',
    storageBucket: 'blood-donation-hci.firebasestorage.app',
    measurementId: 'G-JX5K517LKT',
  );
}
